In [2]:
import numpy

In [3]:
# Is like an Array
n = numpy.arange(27)
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [4]:
type(n)

numpy.ndarray

In [5]:
# Reshaping the n numpy array to 2 Dimensional Array
n.reshape(3,9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [6]:
# Reshaping the n numpy array to 3 dimensional array
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [7]:
# Importing OpenCV Library
import cv2

In [15]:
# Second argument, 1 if you want BGR(Blue, Green, Red)
im_g=cv2.imread("smallgray.png",1)
im_g
# 255 = white color
# 0 = black color
# This Will print 3 rown and 5 columms

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [16]:
# Second argument, 0 if you want to read the image in gray scale
im_g=cv2.imread("smallgray.png",0)
im_g
# 255 = white color
# 0 = black color
# This Will print 3 rows and 5 columms

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [12]:
# Create Images from Numpy arrays
cv2.imwrite("new_small_gray.png",im_g)

True

In [18]:
# Get the first two rows from the Numpy Array
im_g[0:2]

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147]], dtype=uint8)

In [23]:
# Slicing Values from the Numpy Array
im_g[0:2,2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [20]:
# Show the Numpy Array Shape, 3 rows and 5 columns 
im_g.shape

(3, 5)

In [22]:
# Iterating throw ROWS in a Numpy Array
for i in im_g:
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [24]:
# Iterating throw COLUMNS in a Numpy Array
for i in im_g.T:
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [25]:
# Iterating throw a Numpy Array, showing all the values, 1 by 1
for i in im_g.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [28]:
# Stacking(Horizontaly) a Numpy Array, you have to use a Tuple of Numpy Arrays
ims = numpy.hstack((im_g,im_g))
ims
# OBS: THE ARRAYS MUST HAVE THE SAME DIMENSIONS

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [29]:
# Stacking(Verticaly) a Numpy Array(Concatenate the Array), you have to use a Tuple of Numpy Arrays
ims = numpy.vstack((im_g,im_g))
ims
# OBS: THE ARRAYS MUST HAVE THE SAME DIMENSIONS

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [31]:
# Produce a List of Numpy Array
lst = numpy.vsplit(ims,3)
lst

[array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147]], dtype=uint8),
 array([[209, 134, 255,  97, 182],
        [187, 158, 104, 121, 143]], dtype=uint8),
 array([[198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8)]

In [32]:
type(lst)

list

In [33]:
lst[0]

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147]], dtype=uint8)